development:
  adapter: postgresql
  encoding: utf8
  database: NetZero_development
  pool: 5
  username: alyssa
  password: ""
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: NetZero_test
  pool: 5
  username: alyssa
  password: ""
  host: localhost

